/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.king.fragement.jni;

public class ExampleJNI {
  public final static native long getuid();
  public final static native void PI_set(double jarg1);
  public final static native double PI_get();
  public final static native int fact(int jarg1);
  public final static native int mod(int jarg1, int jarg2);
  public final static native String getTime();
  public final static native String toUpperCase(String jarg1);
}
