/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.king.fragement.jni;

public class UnixJNI {
  public final static native long getuid();
  public final static native int MAX_HEIGHT_get();
}
