/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_king_fragement_JniTest */

#ifndef _Included_com_example_king_fragement_JniTest
#define _Included_com_example_king_fragement_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_king_fragement_JniTest
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_king_fragement_JniTest_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_example_king_fragement_JniTest
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_king_fragement_JniTest_getStringFromNative
  (JNIEnv *, jobject);

/*
 * Class:     com_example_king_fragement_JniTest
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_king_fragement_JniTest_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
