#include <stdio.h>
#include <android/log.h>
#include "com_example_king_fragement_JniTest.h"
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_king_fragement_JniTest */

/*
 * Log
 * required #include<android/log.h>
 * */
#ifndef LOG_TAG
#define LOG_TAG "ANDROID_JNI"
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
#endif
/*
 * 需要指定java文件来链接
 * */
#ifndef _Included_com_example_king_fragement_JniTest
#define _Included_com_example_king_fragement_JniTest
#ifdef __cplusplus

extern "C" {
#endif
#endif
/*
 * Class:     com_example_king_fragement_JniTest
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
//JNIEXPORT jstring JNICALL Java_com_example_king_fragement_JniTest_getName
//        (JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_com_example_king_fragement_JniTest_getStringFromNative
        (JNIEnv *env, jobject jobj) {
    LOGD("Log from ndk");
    return (*env)->NewStringUTF(env, "hello-jni");
}


//JNIEXPORT jstring JNICALL Java_com_example_king_fragement_JniTest_stringFromJNI


//        (JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif

